import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import prettier from 'prettier';

/**
 * This initialises the directory that all generated code files will be written to
 */
function setupLibDir(): string {
  const packageRoot = findPackageRoot(__dirname);
  const dir = resolve(packageRoot, 'dist/lib');

  mkdirSync(dir, { recursive: true });

  return dir;
}

export async function writeLibFile(
  filename: string,
  content: string,
  minify?: boolean
): Promise<void> {
  const uiDir = setupLibDir();
  const filePath = resolve(uiDir, filename);

  const header = `// Generated by Dust CLI
// This file is auto-generated - do not edit manually

`;

  const contentWithHeader = header + content;

  let finalContent: string;

  if (minify) {
    // For minified output, skip prettier formatting and minimize whitespace
    finalContent = minifyJS(contentWithHeader);
  } else {
    finalContent = await prettier.format(contentWithHeader, {
      filepath: filePath,
      parser: getParserForFile(filename),
    });
  }

  writeFileSync(filePath, finalContent);
}

function getParserForFile(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase();
  switch (ext) {
    case 'js':
    case 'jsx':
      return 'babel';
    case 'ts':
    case 'tsx':
      return 'typescript';
    case 'json':
      return 'json';
    default:
      return 'babel';
  }
}

function minifyJS(code: string): string {
  // TODO: Make this more robust or find a 3rd party library to do this
  return (
    code
      // Remove single-line comments but preserve line breaks for multi-line context
      .replace(/\/\/.*$/gm, '')
      // Remove multi-line comments
      .replace(/\/\*[\s\S]*?\*\//g, '')
      // Remove extra whitespace but preserve necessary spaces
      .replace(/\s+/g, ' ')
      // Clean up specific patterns
      .replace(/;\s+/g, ';')
      .replace(/{\s+/g, '{')
      .replace(/\s+}/g, '}')
      .replace(/,\s+/g, ',')
      .replace(/\(\s+/g, '(')
      .replace(/\s+\)/g, ')')
      .replace(/\[\s+/g, '[')
      .replace(/\s+]/g, ']')
      // Remove leading/trailing whitespace
      .trim()
  );
}

function findPackageRoot(startDir: string): string {
  let currentDir = startDir;
  while (currentDir !== dirname(currentDir)) {
    if (existsSync(resolve(currentDir, 'package.json'))) {
      return currentDir;
    }
    currentDir = dirname(currentDir);
  }
  throw new Error('Could not find package.json');
}
